### ISSUE TITLE
the critics updating

### ISSUE THREAD

**Issue by Fujiry0** [DAA233/generative-inpainting-pytorch#11]
Hi! thank you for your code. According to the original paper, Algorithm 1 updates the two critics for 5 time every iteration. However, in your implementation, it updates both generator and critics at the same time every iteration.
Please tell me about that. I am sorry if my interpretation is mistaken.

<img width="426" alt="スクリーンショット 2019-07-24 16 28 42" src="https://user-images.githubusercontent.com/36188677/61773842-900dd680-ae30-11e9-8b67-426a9ad0d51c.png">
<img width="569" alt="スクリーンショット 2019-07-24 16 28 10" src="https://user-images.githubusercontent.com/36188677/61773821-87b59b80-ae30-11e9-83b9-77eb84122337.png">

**Comment by DAA233** [comment]
Thanks for your checking. You are right, I have ignored this setting. Sorry for the mistakes I have made. I will fix the bug later.

For now, you can just modify like the following:
```python
# Update D
if iteration % 5 == 0:
    trainer_module.optimizer_d.zero_grad()
    losses['d'] = losses['wgan_d'] + losses['wgan_gp'] * config['wgan_gp_lambda']
    losses['d'].backward()
    trainer_module.optimizer_d.step()

# Update G
...
```

**Comment by Fujiry0** [comment]
thank you for your quick response! however, i think you should update generator every 5 iterations instead of critics.

**Comment by DAA233** [comment]
You are right. It should be:
```python
# Update D
trainer_module.optimizer_d.zero_grad()
losses['d'] = losses['wgan_d'] + losses['wgan_gp'] * config['wgan_gp_lambda']
losses['d'].backward()
trainer_module.optimizer_d.step()

# Update G
if iteration % 5 == 0:
    trainer_module.optimizer_g.zero_grad()
    losses['g'] = losses['l1'] * config['l1_loss_alpha'] \
                  + losses['ae'] * config['ae_loss_alpha'] \
                  + losses['wgan_g'] * config['gan_loss_alpha']
    losses['g'].backward()
    trainer_module.optimizer_g.step()
```

Maybe we should separate the `trainer.forward` function to save the redundant G loss computing.

**Comment by Fujiry0** [comment]
I agree. i'm looking forward to your new version code.
thanks a lot!

**Comment by DAA233** [comment]
Hi @Fujiry0, I have updated the code to add `n_critic` to the WGAN-GP loss.

I didn't  separate the `trainer.forward` function since there are some comparable parts with the `DataParallel` module. You are welcomed to check the updated code.

**Comment by Fujiry0** [comment]
I'll check it out later. Many thanks!
