### ISSUE TITLE
bad inpainting results on CelebA?

### ISSUE THREAD

**Issue by zhengbowei** [DAA233/generative-inpainting-pytorch#13]
Thank you for your code.But not I use your code to train CelebA datasets, it shows a bad inpainting effect in the validation of every 1000 iterations during the training phase.(hole_benchmark folder)。
Have you ever trained on this datasets(CelebA)? Can a well-trained model be provided?

**Comment by DAA233** [comment]
How many iterations you have used to train the model? 

I have trained the model on the CelebA dataset in the early version of this repo but there are no pre-trained models now.

**Comment by zhengbowei** [comment]
I found that because my iterations are too few, now the image restoration effect is very good, thank you for your implementation, it has helped me a lot. 



---Original---

**Comment by DAA233** [comment]
Thanks for your feedback! It sounds great!

**Comment by CyanideBoy** [comment]
@zhengbowei How many iterations did you finally train for good results? Is 500k good enough? I am actually trying to train it on Places2

**Comment by ming1993li** [comment]
> Thanks for your feedback! It sounds great!

Dear author, do you have pre-trained weights on CelebA? Thank you very much.
