### ISSUE TITLE
Difference between official inplementation

### ISSUE THREAD

**Issue by OwalnutO** [DAA233/generative-inpainting-pytorch#15]
Thanks for your brilliant code

One question. In official implementation,  both fine and coarse generator share one single encoder network. But in your implementation, you use different encoders for these two generator. Could this operation provide better performance?

Thanks~

**Comment by DAA233** [comment]
I don't think so. In my view, according to the official implementation [here](https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_model.py), there are no weight sharing between the fine and coarse generator.

**Comment by OwalnutO** [comment]
Sorry, I confused with another project. Ha-ha

Thanks, anyway
