### ISSUE TITLE
Why use F.interpolate in networks.py?

### ISSUE THREAD

**Issue by dayeguilaiye** [DAA233/generative-inpainting-pytorch#16]
In networks.py line 79, in the coarse model, i found that you have used "interpolate" function, but in [tensorflow version](https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_model.py#L63), they used an deconv layer, is there any reason?
I'm learning this paper, thanks a lot !

**Comment by DAA233** [comment]
Actually, they didn't use the deconv layer in the tensorflow version. Refers to [here](https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_ops.py#L66), they use `resize` and `gen_conv` in the `gen_deconv`。The `resize` in tensorflow is just like the `interpolate` in pytorch.

**Comment by dayeguilaiye** [comment]
> Actually, they didn't use the deconv layer in the tensorflow version. Refers to [here](https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_ops.py#L66), they use `resize` and `gen_conv` in the `gen_deconv`。The `resize` in tensorflow is just like the `interpolate` in pytorch.

wow, thank you for your explanation!
