### ISSUE TITLE
Leaf Variable has been moved to graph interior

### ISSUE THREAD

**Issue by Shivanshmundra** [DAA233/generative-inpainting-pytorch#17]
![image](https://user-images.githubusercontent.com/25545489/68217441-9b17fb80-0008-11ea-8150-cd4bde9108a3.png)
Any idea why this error is occurring?

**Comment by DAA233** [comment]
Sorry, I don't have any idea about the error.

This repo was tested on PyTorch 1.0. Which version of PyTorch are you using? Or have you modified the losses?

**Comment by Shivanshmundra** [comment]
I didn't modify, I even tried disabling all local critic losses. I am using Pytorch 1.2 version.

**Comment by Shivanshmundra** [comment]
The error is coming in the ```Grad_penalt``` function.

**Comment by deepankarc** [comment]
Replace `line 96`  ('interpolates = autograd.Variable(interpolates, requires_grad=True)') in 'calc_grad_penalty' with 'interpolates.requires_grad_()'. For further information see: https://discuss.pytorch.org/t/leaf-variable-was-used-in-an-inplace-operation/308/2

**Comment by DAA233** [comment]
@deepankarc Thanks for your solution. However, `interpolates.requires_grad_()` doesn't work for me with PyTorch 1.2 and PyTorch 1.3. I solved the problem with `interpolates.requires_grad_().clone()` or `interpolates = autograd.Variable(interpolates, requires_grad=True).clone()`, just as descripted in your above link.
