### ISSUE TITLE
I do not get the same output as the examples

### ISSUE THREAD

**Issue by gilShamai** [DAA233/generative-inpainting-pytorch#22]
I downloaded the PyTorch model and ran it on the examples.
Here is the output I get:
![output](https://user-images.githubusercontent.com/6123830/69980370-c6730500-1538-11ea-9562-7296aab41c53.png)

Any idea why?

**Comment by DAA233** [comment]
Your result looks very bad. However, I just tested again with PyTorch 1.0.1 and PyTorch 1.2.0 on the [pretrained model](https://drive.google.com/open?id=1qbfA5BP9yzdTFFmiOTvYARUYgW1zwBBK) (provided in README) and the results are both good.

Maybe the model weight path is wrong? If the model weight has been loaded successfully, you should see the following log:
```log
Resume from checkpoints/imagenet/hole_benchmark at iteration 430000
Saved the inpainted result to examples/output.png
```
