### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by liangyufz** [DAA233/generative-inpainting-pytorch#23]
hi ,
   Could you please tell me which gpu you are using to trian the model ?
  I use 1 1080ti  11Gb  with batch size 8 or less ,   or  3 1080ti 11Gb with batch size 36 or less,  OOM occured.

**Comment by DAA233** [comment]
I use one TITAN X 12GB with batch size 16 or three of them with batch size 48 and no OOM there.

In my view, batch size 8 is small enough for training on a 11GB GPU. Maybe you can try batch size 1 to exclude other possible reasons.

**Comment by liangyufz** [comment]
观察了下,显存会不停增长直到OOM, 并不是增长到稳定.请问你有过这个现象么

**Comment by DAA233** [comment]
这个正常

**Comment by liangyufz** [comment]
目测是pytorch版本问题,我使用的1.3,有些放到gpu上变量不能及时释放?
换到1.0之后,一切正常,感谢~
另外,请问按照你给的默认配置,大概训练了多久以及多少次迭代,才到你的效果?

**Comment by DAA233** [comment]
哦哦，用 pytorch 1.2+版本似乎 gradient penalty 存在点问题，最近在测试。

训练大概需要5~7天。
