### ISSUE TITLE
Problems with test results

### ISSUE THREAD

**Issue by summerwbb** [daa233/generative-inpainting-pytorch#30]
Thank you very much for sharing. When I was testing my own graph, there was a fog in the results, and the results were not clear.
![image](https://user-images.githubusercontent.com/40291885/77498411-88ed0b80-6e8a-11ea-8043-b752859569d5.png)

**Comment by daa233** [comment]
The code in this repo is just for a PyTorch implementation of deepfill v1, which does not support non-regular shape masks. On the other hand, you may train the model on your own dataset to get better performance. I don't know if you have trained on your own dataset.

**Comment by summerwbb** [comment]
thank you very much!
