### ISSUE TITLE
 Is the real cos similarity being used in Contextual Attention?

### ISSUE THREAD

**Issue by PangzeCheung** [daa233/generative-inpainting-pytorch#37]
cos similarity need calculate norm of the patch. But in the code, I am not find where to calculate the norm of the xi.
max_wi = torch.max(torch.sqrt(reduce_sum(torch.pow(wi, 2),axis=[1, 2, 3],keepdim=True)),escape_NaN)
wi_normed = wi / max_wi
yi = F.conv2d(xi, wi_normed, stride=1)   # [1, L, H, W]
I am confuse about this question, thank you very much~

**Comment by daa233** [comment]
Refers to https://github.com/JiahuiYu/generative_inpainting/issues/281.
