### ISSUE TITLE
Error backward loss generator

### ISSUE THREAD

**Issue by htn274** [daa233/generative-inpainting-pytorch#38]
I trained the model on my own dataset and got the error: 
![image](https://user-images.githubusercontent.com/26211514/83889054-dfbd6e00-a774-11ea-8e0d-fa514f98e127.png)
I found that this line resulted in error.
https://github.com/daa233/generative-inpainting-pytorch/blob/ee1fd75f5253b579cd12ede8b7ed27f3ee6e747d/train.py#L135
Could you help me fix this? 
Thank you!

**Comment by daa233** [comment]
Could you post the error information here?

**Comment by htn274** [comment]
` File "train.py", line 182, in <module>
    main()
  File "train.py", line 178, in main
    raise e
  File "train.py", line 140, in main
    losses['g'].backward()
  File "/home/duongbao/miniconda3/envs/nu/lib/python3.6/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/duongbao/miniconda3/envs/nu/lib/python3.6/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [65536, 1]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!`

This is the error I received when I run `python train.py --config configs/config.yaml`

**Comment by daa233** [comment]
Not sure about the error. You may find solutions [here](https://github.com/NVlabs/FUNIT/issues/23).

**Comment by vlad-i** [comment]
I have also come across this issue, will post if I have a fix

**Comment by vlad-i** [comment]
> Not sure about the error. You may find solutions [here](https://github.com/NVlabs/FUNIT/issues/23).

I have also set all inplace arguments to false as suggested by the top voted comment there, to no avail.

**Comment by vlad-i** [comment]
> > Not sure about the error. You may find solutions [here](https://github.com/NVlabs/FUNIT/issues/23).
> 
> I have also set all inplace arguments to false as suggested by the top voted comment there, to no avail.

Now I've downgraded Pytorch to 1.0.0 and torchvision to 0.2.0 and it is no longer receiving this error. @htn274  what torch and torchvision versions do you have?

**Comment by Fuzesunshine** [comment]
You can find the solution [here](https://discuss.pytorch.org/t/runtimeerror-one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-operation-code-worked-in-pytorch-1-2-but-not-in-1-5-after-updating/87327)

You can modify the code from [line 55](https://github.com/daa233/generative-inpainting-pytorch/blob/c46a706c560caf92044c9b79b3e69fc27257670c/trainer.py#L56) to [line 77](https://github.com/daa233/generative-inpainting-pytorch/blob/c46a706c560caf92044c9b79b3e69fc27257670c/trainer.py#L77) as 
`                if compute_g_loss:
                    # Update D & G
                    trainer_module.optimizer_d.zero_grad()
                    losses['d'] = losses['wgan_d'] + losses['wgan_gp'] * config['wgan_gp_lambda']
                    trainer_module.optimizer_g.zero_grad()
                    losses['g'] = losses['l1'] * config['l1_loss_alpha'] \
                                  + losses['ae'] * config['ae_loss_alpha'] \
                                  + losses['wgan_g'] * config['gan_loss_alpha']
                    losses['d'].backward()
                    losses['g'].backward()
                    trainer_module.optimizer_d.step()
                    trainer_module.optimizer_g.step()
                else:
                    # Update D
                    trainer_module.optimizer_d.zero_grad()
                    losses['d'] = losses['wgan_d'] + losses['wgan_gp'] * config['wgan_gp_lambda']
                    losses['d'].backward()
                    trainer_module.optimizer_d.step()`
and the bug will be fixed :)
