### ISSUE TITLE
How should i get attention Visualization?

### ISSUE THREAD

**Issue by zhangbaijin** [daa233/generative-inpainting-pytorch#39]
Thanks for your code, it's amazing! But how  should i get attention Visualization? What command should i run?

**Comment by daa233** [comment]
Thanks for your attention.

The attention visualization is already implemented in the code. The `offset_flow` is the attention map in `trainer.py`.

**Comment by zhangbaijin** [comment]
Thanks for your time,there is a problem ,`parser.add_argument('--imageA', default='./examples/imagenet/imagenet_patches_ILSVRC2012_val_00000827_output.png', type=str, help='Image A as background patches to reconstruct image B.')
    parser.add_argument('--imageB', default='./examples/imagenet/imagenet_patches_ILSVRC2012_val_00000827_input.png', type=str, help='Image B is reconstructed with image A.')
    parser.add_argument('--imageOut', default='./examples/imagenet/result.png', type=str, help='Image B is reconstructed with image A.')`
and i set the config,but it doesn't work? How to slove it ?

**Comment by zhangbaijin** [comment]
` def test_contextual_attention(args):
E       fixture 'args' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
`

**Comment by zhangbaijin** [comment]
` def test_contextual_attention(args):
       fixture 'args' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
`

**Comment by zhangbaijin** [comment]
```
def test_contextual_attention(args):
E       fixture 'args' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

**Comment by daa233** [comment]
`test_contextual_attention` is a test function to verify the correctness of the contextual attention module. It is called in the `__main__` in [`networks.py`](https://github.com/daa233/generative-inpainting-pytorch/blob/master/model/networks.py#L559).

It seems that you didn't call it by `python networks.py` with arguments correctly.

**Comment by zhangbaijin** [comment]
应该是我参数没设好，但是我有点不清楚这个参数应该怎么设置？

**Comment by daa233** [comment]
应该是 `python networks.py --imageA xxx.png --imageB xxx.png --imageOut xxx.png` 就可以了

**Comment by zhangbaijin** [comment]
好的老哥，谢谢，么的问题了
