### ISSUE TITLE
test image resolution 

### ISSUE THREAD

**Issue by DragonDeux** [daa233/generative-inpainting-pytorch#43]
Hello,

I have a very basal question please, could i use a image of 1920*1080 to do test with trained data? thank you very much for helping

**Comment by daa233** [comment]
It is possible but there may be some *hard code* in the repo for image size 256\*256 (e.g. contextual attention module, not sure). Sorry, I don't have time to adapt the code for you. You may try to run it with 1920\*1080 and then revise the errors.
