### ISSUE TITLE
在训练时遇到问题File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 572, in __next__     raise StopIteration StopIteration

### ISSUE THREAD

**Issue by ZHANG-hengzhi** [daa233/generative-inpainting-pytorch#47]
大神，请问训练时出现这错误应该怎么修改呀，求大神指点

**Comment by daa233** [comment]
可能是因为没有读到数据

**Comment by ZHANG-hengzhi** [comment]
大神请问一下，线程是说num_works吗，我设置成0或1也都不行，求大神指点，非常感谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Du Ang"<notifications@github.com&gt;; 
发送时间: 2020年9月10日(星期四) 晚上8:09
收件人: "daa233/generative-inpainting-pytorch"<generative-inpainting-pytorch@noreply.github.com&gt;; 
抄送: "张恒志"<594300065@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [daa233/generative-inpainting-pytorch] 在训练时遇到问题File &quot;D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py&quot;, line 572, in __next__     raise StopIteration StopIteration (#47)





 
可能是因为没有读到数据
 
—
您收到此消息是因为您编写了线程。
直接回复这封电子邮件，在GitHub上查看，或取消订阅.

**Comment by daa233** [comment]
`num_worker` 是加载数据的线程数，应该跟你这个错误没关系。你可以打印 dataloader 里的数据路径看看，是不是路径指定错了。

**Comment by ZHANG-hengzhi** [comment]
好的，非常感谢大神，我是个新手，研究一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Du Ang"<notifications@github.com&gt;; 
发送时间: 2020年9月10日(星期四) 晚上8:18
收件人: "daa233/generative-inpainting-pytorch"<generative-inpainting-pytorch@noreply.github.com&gt;; 
抄送: "张恒志"<594300065@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [daa233/generative-inpainting-pytorch] 在训练时遇到问题File &quot;D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py&quot;, line 572, in __next__     raise StopIteration StopIteration (#47)





 
num_worker 是加载数据的线程数，应该跟你这个错误没关系。你可以打印 dataloader 里的数据路径看看，是不是路径指定错了。

**Comment by zhangsiyuan6** [comment]
Can you tell me how much your batchsize, niter is set to, and how many pictures you use?

**Comment by ZHANG-hengzhi** [comment]
batchsize=2， niter=500, pictures=600。非常抱歉大神，才看到信息，求大神指教




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhangsiyuan6"<notifications@github.com&gt;; 
发送时间: 2020年9月23日(星期三) 下午2:52
收件人: "daa233/generative-inpainting-pytorch"<generative-inpainting-pytorch@noreply.github.com&gt;; 
抄送: "张恒志"<594300065@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [daa233/generative-inpainting-pytorch] 在训练时遇到问题File &quot;D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py&quot;, line 572, in __next__     raise StopIteration StopIteration (#47)





 
Can you tell me how much your batchsize, niter is set to, and how many pictures you use?

**Comment by zhangsiyuan6** [comment]
Hello, I used 5000 pictures, set the batchsize to 16, ran 50000 times and 100000 times respectively. Why is the effect of 100000 times worse?If you know, please reply me, thank you very much!

**Comment by 01SHENyankun** [comment]
你好，能不能加个联系方式指导一下小白复现这篇论文，我的qq：2635505974

**Comment by stu977** [comment]
> 大神，请问训练时出现这错误应该怎么修改呀，求大神指点

请问一下您这个问题最后怎么解救的呀
