### ISSUE TITLE
How can I make use of the FLOW argument?

### ISSUE THREAD

**Issue by DanielMallia** [DAA233/generative-inpainting-pytorch#51]
I was looking into the code and there is a flow argument but I can't find an example that uses it so I don't know how I can make it work.

Thanks for your help

**Comment by daa233** [comment]
It is just used for the visualization of the contextual attention map.

**Comment by DanielMallia** [comment]
Thanks for the reply. I'm attempting to modify it to work on videos and I was thinking of making use of the flow between frames but I think I would need to implement a separate one. Additionally I would need to also be able to pass in multiple frames at a time into the GAN which I still have to understand from the code, but this is some great and understandable work. Thanks and Great Job

**Comment by daa233** [comment]
Thanks!
