### ISSUE TITLE
question about CA details

### ISSUE THREAD

**Issue by fiftywu** [DAA233/generative-inpainting-pytorch#56]
https://github.com/daa233/generative-inpainting-pytorch/blob/c6cdaea0427b37b5b38a3f48d4355abf9566c659/model/networks.py

line: 323

yi = F.conv_transpose2d(yi, wi_center, stride=self.rate, padding=1) / 4. 

I do not know why divide 4?

can you tell me?

thanks

**Comment by 01SHENyankun** [comment]
能加个联系方式，一起学习嘛。2635505974

**Comment by daa233** [comment]
@fiftywu see here https://github.com/JiahuiYu/generative_inpainting/issues/22#issuecomment-385007226
