### ISSUE TITLE
程序运营问题

### ISSUE THREAD

**Issue by 01SHENyankun** [DAA233/generative-inpainting-pytorch#57]
您好，冒昧打扰，请您原谅！
  这篇文章是我想复现的第一篇文章，我在网上找到了您发的代码，但是运行的时候出现了一些问题，例如：找不到路径，等等。所以，才想起来找您讨教一二。
  如果您有空闲时间，愿意指教一二，本人将不胜感激！我的联系方式qq：2635505974

**Comment by daa233** [comment]
暂时没有时间做这个，可以把遇到的问题贴到这里。

**Comment by 01SHENyankun** [comment]
不好意思，刚刚看见
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "daa233/generative-inpainting-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月27日(星期四) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [daa233/generative-inpainting-pytorch] 程序运营问题 (#57)





 
暂时没有时间做这个，可以把遇到的问题贴到这里。

**Comment by 01SHENyankun** [comment]
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 4.00 GiB total capacity; 2.48 GiB already allocated; 0 bytes free; 2.77 GiB reserved in total by PyTorch)
报错的是这样的，我尝试把batch_size调小也没有解决问题，在网上说加with torch.no_grad():,但是我不知道加在哪里，所以请教一下，这是我复现的第一篇论文，意义重大

**Comment by 01SHENyankun** [comment]
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 4.00 GiB total capacity; 2.48 GiB already allocated; 0 bytes free; 2.77 GiB reserved in total by PyTorch)
报错的是这样的，我尝试把batch_size调小也没有解决问题，在网上说加with torch.no_grad():,但是我不知道加在哪里，所以请教一下，这是我复现的第一篇论文，意义重大

**Comment by daa233** [comment]
可以把显卡型号发一下，看上去是显存不够导致的
