### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by mauricewells** [DAA233/generative-inpainting-pytorch#65]
I run with the command below, but your code makes error message like above.

python test_single.py --image examples/imagenet/imagenet_patches_ILSVRC2012_val_00008210_input.png --mask examples/center_mask_256.png --output examples/output.png

how can i fix that?

**Comment by daa233** [comment]
Could you post your error message or logs here?

**Comment by st0421** [comment]
i resolved with !pip install pyyaml==5.4.1

https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col

**Comment by nathanaelhuh** [comment]
Fixed by replacing ```return yaml.load(stream)``` with ```return yaml.load(stream, Loader=yaml.FullLoader)``` on line 476 of /utils/tools.py
