### ISSUE TITLE
ERROR num_samples should be a positive integeral value, but got num_samples=0

### ISSUE THREAD

**Issue by DAA233** [DAA233/generative-inpainting-pytorch#7]
Hello, I am Daisy.
I was really surprised to find out that you've finished this pytorch version of the paper recently. Thanks a lot. However, when I tried to train the model, I can't read the image file right. The error is like this.

ERROR num_samples should be a positive integeral value, but got num_samples=0

May I ask if the format of your training images are like "n02128925_9771.JPEG"? I download them from ILSVRC2012 website->Images-> Training images (Task 1 & 2).(http://www.image-net.org/challenges/LSVRC/2012/nonpub-downloads).
Thanks again!!

---
@daisy91530 I copied [your question](https://github.com/DAA233/generative-inpainting-pytorch/commit/e9289d1815f015422f7aea3c54325425bd7e0c22#commitcomment-34138579) here in case someone meets the same problem.

**Comment by DAA233** [comment]
Thanks for your attention.

It seems that the program didn't find any training images in the `train_data_path`, which configured `configs/config.yaml`. You may check if the `train_data_path` is correct.

The format of training images can be one of the two following ways.
1. Use with `data_with_subfolder: False` in `configs/config.yaml`:
```
train_data_path
    xxx.JPEG
    xxx.JPEG
    xxx.JPEG
    ...
```
2. Use with `data_with_subfolder: True` in `configs/config.yaml`:
```
train_data_path
    class_1_directory
        xxx.JPEG
        xxx.JPEG
    class_2_directory
        xxx.JPEG
        xxx.JPEG
    ...
```

**Comment by daisy91530** [comment]
Thanks a lot! It works!
