### ISSUE TITLE
Code to convert TensorFlow models

### ISSUE THREAD

**Issue by rszeto** [DAA233/generative-inpainting-pytorch#8]
Hello,

I am wondering if you are planning to release the code used to convert the TensorFlow model to PyTorch or, alternatively, converted snapshots for the other datasets used in the original paper (e.g. CelebA, Places).

Keep up the great work!

**Comment by DAA233** [comment]
Sorry, I don't have the code. The TF model was converted by @zphang and I just merged his pull request.
